# Use postgres/example user/password credentials
version: '3.4'

services:
  eshopdb:
    image: postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - eshopdb  
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  postgres_eshopdb:
  pgadmin_data: {}